# Generated by Django 5.1.4 on 2026-06-19 03:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('column', models.CharField(max_length=255)),
                ('nl_description', models.TextField(blank=True)),
                ('regex_pattern', models.TextField()),
                ('flags', models.CharField(blank=True, max_length=8)),
                ('replacement', models.TextField(blank=True)),
                ('match_count', models.PositiveIntegerField(default=0)),
                ('is_undone', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformations', to='datasets.dataset')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
