# Generated by Django 5.1.4 on 2026-06-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformation',
            name='kind',
            field=models.CharField(choices=[('regex', 'Regex replacement'), ('dates', 'Date standardization'), ('phones', 'Phone normalization')], default='regex', max_length=16),
        ),
        migrations.AddField(
            model_name='transformation',
            name='params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='regex_pattern',
            field=models.TextField(blank=True),
        ),
    ]
