# Generated by Django 5.1.4 on 2026-06-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transforms', '0002_transformation_kind_transformation_params_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transformation',
            name='column',
        ),
        migrations.AddField(
            model_name='transformation',
            name='columns',
            field=models.JSONField(default=list),
        ),
    ]
